plugins {
    id "org.jetbrains.kotlin.jvm"
}

repositories {
    mavenCentral()
}

group scratchGroup
version scratchVersion

apply plugin: 'maven-publish'

compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
    kotlinOptions.freeCompilerArgs = [
            "-Xallow-kotlin-package",
            "-opt-in=kotlin.Experimental",
            "-opt-in=kotlin.ExperimentalUnsignedTypes",
            "-opt-in=kotlin.ExperimentalStdlibApi"
    ]
}

compileJava {
    targetCompatibility = "1.8"
    sourceCompatibility = "1.8"
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}

apply from: "../maven.gradle"
